### ISSUE TITLE
Pluralise can be improved

### ISSUE THREAD

**Issue by huochunpeng** [michaelbull/aurelia-hacker-news#21]
I was glancing your html templates, it made me smile when I saw an exactly same value converter `pluralise` as I had in my project.

I thought you might be using the same underneath library I use but you didn’t.

This 👇 lib can help you to do proper English plural, if you don’t mind inflating your js. 
https://github.com/blakeembrey/pluralize

**Comment by michaelbull** [comment]
Hi, thanks for the suggestion.

As it stands, the `pluralise` value converter is used in two places ([1](https://github.com/michaelbull/aurelia-hacker-news/blob/54d32335b6d09983894bd62b09b87697b7e08839/src/components/item-preview.html#L22), [2](https://github.com/michaelbull/aurelia-hacker-news/blob/54d32335b6d09983894bd62b09b87697b7e08839/src/components/item-preview.html#L37)) in the `item-preview` custom element.

The simple solution I've got pluralises these words i.e. point(s) & comment(s), perfectly fine. If the `pluralise` value converter was to be used for a wider range of words in the project then I'd look to adopt a more robust solution, but as it stands I can't really justify adopting a third-party library to pluralise these two words.

Thanks for the suggestion.
